import itertools

ids = "cnjxpritdzhubeseewfmqagkul,cwyxpgitdzhvbosyewfmqagkul,cnfxpritdzhebosywwfmqagkul,cnjxpritdzgvbosyawfiqagkul,cnkxpritdzhvbosyewfmgagkuh,gnjxprhtdzhebosyewfmqagkul,cnjxpriedzevbosyewfjqagkul,cnjxpritdzhpyosyewfsqagkul,cnjxprltdzhvbosyewfmhagkzl,cnjxfritdjhvbosyewfmiagkul,xnjxpritdzhvbosyewfmqagkgn,cnjxpritdzmvzosyewfhqagkul,cljxxritdzhvbosyewfmragkul,cnjxjritdzhvbovyewfmvagkul,cnjxprdtdzhpbosyewvmqagkul,cojxprdtdzhzbosyewfmqagkul,cnjxpritgzhvfgsyewfmqagkul,knjxprptdzhvbosyecfmqagkul,cnjxpritdzhvbvsyeyfmqagkuc,cnjxpritdzhvbosvewfmoagjul,cnjxpritdzhvbosyfwfmbagkjl,cnjxpjitazhvbosfewfmqagkul,cnjtpfitdzhvbosyewfmiagkul,ckjxpritdzhvbysyewfmqagoul,cnjxvritdzhvbfsyewfmqalkul,cnjipqitdzhvbosyewfeqagkul,cnjhpritdzhvbosyewymqjgkul,cnjxprrtdzhvbosyewfmlkgkul,cnjxnritdzhvbopyewfmqaskul,cxjxpritdzhvtosyewjmqagkul,cnjxpritdzhvbjsyewfrqagkwl,cnjxhritdzhubosyewfmqagvul,cnjxpritdzhvbosyyyfmeagkul,cnjxkritdzhvaoeyewfmqagkul,cnjxpritdzhvtotyewfmqazkul,cnjxoriadzhvbosyewfmqcgkul,cnjxpritdzhcbosyewfmkapkul,fnjxprtddzhvbosyewfmqagkul,cnjxmvitdzhvbosyewfmqagrul,cnjxpyitdzhibosyewfmqagktl,cyjxprxtdzhvbosyewbmqagkul,onjxpditdzhvbosyeofmqagkul,cnjxprixdzhvbosuewftqagkul,cnjxpritdrhvaosyewymqagkul,cnjxpritdzhhbokyewfvqagkul,cnjxpritczhvbosyewfmqwgxul,cnjxpribdzqvbnsyewfmqagkul,ynpxpritdzhvbvsyewfmqagkul,cnjxprirdzhvboerewfmqagkul,cnjxpritdxhvbosyewfmgavkul,cnwxprntdzhvbosyewfmqagkuk,cnjxpritzzhvbosyewfmcagktl,bbjxpritdzhvbosyetfmqagkul,cnjxpbitdzhvbosyewrmqagkui,cnjxwrildzcvbosyewfmqagkul,cnqxpoitdzhvbosnewfmqagkul,cnzxpritdzhvbosyewfmqazkfl,cnjxpriddzhvoosyewfmhagkul,znjxpritdzhvbosjewfmqagkur,cnjxpritdzhvbosyewcmfagkuk,cnjxpritdzhvbomyywnmqagkul,cnjxpgitjzhvbosyejfmqagkul,cnjxpkitdzjvbosyewfmqcgkul,cnjxpritduhvbosyewfmqfkkul,cnfxpritdzhvbgsyewfmqwgkul,cnjxpritdzhvbosywufmqaskul,cnjxprittzhvboryswfmqagkul,cndxpritpzrvbosyewfmqagkul,cnjxpritdzhvbosyewfwqazkum,cccxprmtdzhvbosyewfmqagkul,cnjxpzitdzhvlbsyewfmqagkul,cnjxdrigdzhvbosyewfmqagsul,fhjxpritdzhvbosyewfmqagkcl,cnjxpritdzhvdosyewffqagaul,cnjxprikdztvbosyekfmqagkul,cnjxpritdzhvbohiewfmqagkue,cnjxpritdzhvbowyetfmqegkul,cnuxpritdzhvbosyewmmqapkul,qnjxpritdzhvbosyewfmjakkul,cnjxpritdzlvbosyewiaqagkul,cnjxpritdzhpoosyewfmvagkul,cdjxpritdzhvboryewfbqagkul,cnjxppitxzhvbosyewymqagkul,cnjxpywtdzhvboiyewfmqagkul,cnjxpritdzpvbosyezfmqaqkul,cnjppritdghvbosyewfdqagkul,cmjxpritdzhvbosvewfmqagkup,cnjxoritdzhvbosylffmqagkul,cnjxfritdzhvbojyewfmqagkvl,cnjxpritdzhvbozyewgmqlgkul,cnjxlritdzhvbosyewfmqalkug,cnyxprittzhvbosyewfmsagkul,cnjxprytdzcvdosyewfmqagkul,ctjxpritdzhvbosyedfmqagkil,cnjxpvitdzhrbosyewfmqaekul,cnyxyritdzhvbospewfmqagkul,cnjxoritwzhvbosyewrmqhgkul,cnjxpritdzhjbosyqwsmqagkul,cnjzprindzhvbosyewfmqabkul,cnjspritdzhvbosysffmqagkul,cnxxpritdzhvbosyelfmqageul,bnjhpritdzhvbosyewfmzagkul,cnjxbhitdzhdbosyewfmqagkul,cnjxprktdzmvbosyewfmqagkuj,cnjxprixdzhvbqsyewfmqmgkul,cnjxpkitdzhvbosyewfmqagbum,cnjhpritdzhxbosyewfmqagjul,cnjxpritdzzvbosyewuqqagkul,cnjxprhtdzhvuopyewfmqagkul,cnjxpritdzhjqosyewfmqagkgl,cnzxpritdzhvbosyejfmuagkul,cnvxpritoohvbosyewfmqagkul,cnjxpmitdzwvbosyemfmqagkul,cnjoprittzzvbosyewfmqagkul,cnjxpgitdzhvbosytwfmqsgkul,cnjxprrtdehvbosyewfnqagkul,onjxpjitdzgvbosyewfmqagkul,cnjxpmitdzhvbopaewfmqagkul,cnjxpritqzhvbosoewfrqagkul,cnjxpnitdzhvbosyewfmqagkjy,cnsxpritdzhvbosyewfmqjykul,cnjxpriidzhvbosyewfmqxgkut,cnjxpyitdzhnbosyewfgqagkul,cnjxpritdzhbboyyewfmqagsul,cnjxpeitdzsvbosyewfmqabkul,cnjxpritdzhzvosyewfmragkul,cnjrpritdzhmbosyewfmqrgkul,cnjxpritdzhmbosyenfmqaglul,cnjxqrntdzhvboswewfmqagkul,cnjxprdtpzhvbosyewfmqagkcl,cnjxpritdzhvsdsyewfmqagkur,cnjxpritdzhvvosyewumqhgkul,cnzxpritdznvhosyewfmqagkul,ynjypritdzhvbosyewfmqagkuz,cnjxpnitdzhvbocyezfmqagkul,vnjxpritdzhvbfsyewfmjagkul,cnjfpritdzhvbosyewfmqagkzu,cnjxpritdzhbbosyewfmlegkul,cnjxpnitdzhvbosyesfmbagkul,cnjxpritezwvbosyewfmqagkgl,cujxpritdzhqbosyawfmqagkul,cnjxprindzhrbosyerfmqagkul,cntxpritdzhvbosyewfmqauxul,cnjxpvitdzhvbosyepfmqagkuy,cnjxdrqtdzhvbosdewfmqagkul,cnnxpritdzhvvosyenfmqagkul,lnjxphitdzhvbosyewfaqagkul,cngxpritdzhhbobyewfmqagkul,uncxphitdzhvbosyewfmqagkul,cnjxpribdehvbosfewfmqagkul,cnjxppitdqhvbmsyewfmqagkul,gnjxpritkzhvbosyewfbqagkul,znjxpritdzhvbowycwfmqagkul,cnjxpgitdzhvbosyewidqagkul,cnjxhritdzhvbowyswfmqagkul,injxkritdzhvbjsyewfmqagkul,cmjupritgzhvbosyewfmqagkul,cnjxpritdzbvjoeyewfmqagkul,cnjxpritdkhvbosyewlmuagkul,cnkxpritdzhebvsyewfmqagkul,cyjxptitdzhvbosyewfmqagkuv,cnjxpritdzhvbodrewflqagkul,cnjxpratdzhvbksyewfhqagkul,cnjxpoitdzhvbosjewxmqagkul,cnjxprhidzhvbasyewfmqagkul,cnjxpritdzhvbosqewvmqagmul,cnjxoritdzhvbosyzifmqagkul,mnjxpritdzhvbcsyeyfmqagkul,cnjhpritgzhvbosyewfmqngkul,cnjxprijdzevbesyewfmqagkul,cnexprqtdzhvbosyewvmqagkul,cnjxpxitdzhvbosyawfmqmgkul,cnjxpritdzhvbosyirfmqaxkul,cqjxpcitdzhvboslewfmqagkul,cmjxpqitdztvbosyewfmqagkul,cnbxpritdzhvfosyewfmuagkul,cnjxprrtdzhvbosumwfmqagkul,cnjxprttdvhvbossewfmqagkul,cnjxpritdzhvbcsuewfaqagkul,cbjxpritdzhvbosyewfhqalkul,cnjxprithzhvbosjcwfmqagkul,chjxpritdzhvbosyewftcagkul,cnjxprirdchvdosyewfmqagkul,cnjxpritdxhvbosyewfmqcgkal,cnjxpriidchvbosrewfmqagkul,cnjhprizdzhvbosyewfmqagvul,cnjwpritdzhpbosyewfmqaqkul,cnjxpgitfzhvbosyxwfmqagkul,cnjxpjiedzhvbosywwfmqagkul,cnjxpritdzhvbosyewfpqynkul,xnixlritdzhvbosyewfmqagkul,cnjxoritdznvbosyehfmqagkul,cnjxpritdzhvbjsyewsmqagcul,lnjxpritdzhvkosyewjmqagkul,cnjxpritdzhvbosyedfiqvgkul,cnjxpritdzhqbdsyerfmqagkul,cnjxpritdzavbosyywfmqagvul,dmjxprithzhvbosyewfmqagkul,cnjxpriqdzhvnosyeofmqagkul,cnjxpritdxhvboszewfmqkgkul,cnjxpritdzxvbosjewymqagkul,cnjxpritdzngbosyewfmqugkul,cajxpritdnhvbosyerfmqagkul,cnsxpritdzhvbosymwfmqagcul,cnjxoritdzhvbosyewrmqhgkul,cnjxpritdzhvposyewfmqagkwo,cnjxpriazzhvbosyeufmqagkul,cnjxrritdzhvbosymhfmqagkul,cnjxprztdzhvbosyewfmqtgkum,cnjxpritdzhvbmsyewfmqatkun,cnuxpritdzhvbosyewfmqagvur,ctjxxritdzhvbosyewfvqagkul,cnjxpritdzlvbosyevfmqagkll,cnjxpritdzhlbosyewfmqagasl,cnjxpritwzhvbosyewfcxagkul,cyjxpritdzhfbosyewfmqagcul,cnjxpritxghvkosyewfmqagkul,ctjxpritdjhvbosyewfmqkgkul,cnjxpritxzhvbosyewjmbagkul,unjxpritdzhkbosyewfmqaghul,cnjoprqtdzhvbosyewzmqagkul,rnjxprgtgzhvbosyewfmqagkul,cnjgpqitdzhvbosyewfaqagkul,cnjxpritdzuybosyewfmqagful,cnjxprqtdahvbosyewfnqagkul,cnjxpritdzhmkhsyewfmqagkul,wnjxpritdzhvbosiewfmqagkml,cnjmpritdzhvbosyjwfmqagkdl,cnjopritdzhvbksyewfmqrgkul,cnlxpritdzhvbosyewfmomgkul,cgjxpritdzhvbbsyewfmxagkul,cnaxpritdvhvnosyewfmqagkul,cnjxprijdzhvbkmyewfmqagkul,cnjxpritdzhvposyewzmqagkuz,cnuxpuitdzdvbosyewfmqagkul,cnjxprifdzjvbosyewfyqagkul,cnhspritdzhvbosyewfmqaghul,cnjxprcbdzfvbosyewfmqagkul,lnjapritdzhvbosyewfmqegkul,cnjxprisszhvbosyewqmqagkul,cnjxpritdzhvbosyeifmsagoul,cnjxpritrfhvbosyewfmqagkuz,cnjxkritdzmvboqyewfmqagkul,cnjxpritdzhvbosyedfmqzgkzl,cnjxprifdzhvbosyswfmqagksl,cnjxoritdzhvbosyxwfmhagkul,cnjhpritdzzvbosfewfmqagkul,cnjxprityjhvbomyewfmqagkul,cnjbpritdzhvbosyywfmqagkuf,cnjxprrtdzhvbosyewgmqagtul"

# PART ONE
# these were needed for the second part
correct_box_ids = []

def get_checksum(ids):
	box_ids = ids.split(",")
	two = 0
	three = 0

	for word in box_ids:
		deux = True
		troi = True
		for letter in word:

			if deux:
				if word.count(letter) == 2:
					# print('has two {}s: '.format(letter), word)
					two += 1
					deux = False

					if word not in correct_box_ids:
						correct_box_ids.append(word)

			if troi:
				if word.count(letter) == 3:
					# print('has three {}s: '.format(letter), word)
					three += 1
					troi = False

					if word not in correct_box_ids:
						correct_box_ids.append(word)

	print('two: ', two)
	print('three: ', three)


get_checksum(ids)
# multiply the number of twos by the number of threes to get the checksum


# PART TWO
# find the two ids with one letter switched in the same location
def find_differences(ids):
	# itertools: basically creating tuples of the id and the ones before/after it WITHOUT repeating **important
	for id1, id2 in itertools.combinations(ids, 2):
		diffs = 0
		same = []
		different = []
		# zip is once again going to create a tuple for us, easier to compare
		for a, b in zip(id1, id2):
			if a == b:
				same.append(a)
			else:
				different.append(a)
				diffs += 1
		if diffs == 1:
			print('differences: {}'.format(different), 'similarities: {}'.format(same), id1, id2)

find_differences(correct_box_ids)




